POST http://localhost:8080/api/application/users
Content-Type: application/json
instance: bnVsbF9ydW50aW1lSWQ6MWM0MzY3ZWUtN2M4Mi00MWIwLWIwMjYtMThkM2JlMmMwZjQ1X3J1bnRpbWVab25lZERhdGVUaW1lOjIwMjAtMTEtMDlUMjM6NTE6MTcuOTIxNzI3KzAxOjAwW0V1cm9wZS9XYXJzYXdd

{
  "login": "oa@ij.sd",
  "password": "oijaodij"
}

###
